services:
  - type: web
    name: servicio-intermedio-final
    env: java
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/serviciointermedio-0.0.1-SNAPSHOT.jar"
    plan: free